### ISSUE TITLE
Integrate the synthesizers interface from the old prototype

### ISSUE THREAD

**Issue by babausse** [modular-synthesizer/roadmap#1]
## Context

* A first working prototype for the application was created in this repository : https://github.com/modular-synthesizer/frontend
* The application, and the current frontend at https://github.com/modular-synthesizer/nuxt-frontend are both developed in VueJS
* The current frontend is in VueJS 3 + Nuxt 3, the prototype was in pure VueJS 2

## Needs

As a _logged in user_  
I want to be able to _manipulate and link modules and parameters in a dedicated synthesizer interrface_  
So that I can _use the core features of the application_

## Notes

For now we don't want to implement anything more than the prototype. Nodes will be created just as they are created in it, by specifying the tool used to create them. Routes should normally be already created on the API to satisfy all needs for reimplementation.

## Links

- [x] https://github.com/modular-synthesizer/frontend/issues/8
- [x] https://github.com/modular-synthesizer/frontend/issues/9
- [x] https://github.com/modular-synthesizer/frontend/issues/10
- [x] https://github.com/modular-synthesizer/frontend/issues/12
- [x] https://github.com/modular-synthesizer/frontend/issues/13

**Comment by babausse** [comment]
Closed as the 1.0.0 has been tagged and the application is now deployed in a production environment.
