### ISSUE TITLE
Make the interface suitable for mobile devices

### ISSUE THREAD

**Issue by babausse** [modular-synthesizer/roadmap#16]
## Context

As the application is mainly a production prototype with a slightly better code quality, it lacks some features, mainly being "mobile-first". Nowadays mobiles are a great part of the used devices to display a website and we should be able to access data throughout this medium just as on a desktop. Interfaces should be reworked to be usable on a mobile device, aither for the administration part, or the synthesizer stage itself.

## Subtasks

* [ ] Make the administration interface mobile suitable, each tab of the desktop left menu MUST be accessible on the device with ease
* [ ] Make the tool edition/creation mobile suitable. We MUST be able to access any tab, and to access the preview easily
* [ ] Make the synthesizer stage mobile suitable. This includes any event to drag'n'drop, or zoom on modules
* [ ] Make modules mobile-suitable. This includes mainly drag'n'drop events, deletion and creation of modules
* [ ] Make parameters mobile-suitable. This mainly means giving the users a way to interact with them and edit the value of a knob
* [ ] Make links and ports mobile-suitable. This mainly means having a way to easily create or delete links between ports on a mobile device

## Notes

* The behaviours on desktop SHOULD be changed as little as possible to keep the current interface correctly running
* Some studies MIGHT be necessary to convert some elements to mobile.
