### ISSUE TITLE
Have the subscription confirmed with email

### ISSUE THREAD

**Issue by babausse** [modular-synthesizer/roadmap#7]
## Needs

As an _anonymous user_  
I want to be able to _confirm a subscription request to the service by a link sent by mail_  
So that I can _validate my email and create my account_

## Architectural overview

* Accounts __MUST NOT__ be created as `valid` with the `POST /accounts` route
* The `POST /accounts` route __MUST__ create the account with a validation status and an attach validation request with a `token`
* The token of the validation request will be used on a `POST /validations/:token` to validate the account
* Until he's validated, an account __CANNOT__ be used to login on the application
* When logging in on a non-validated account, the user will be prompted why he can't, and have the choice to send another validation request
* A new validation request will make the previous requests invalid

**Comment by babausse** [comment]
## API Tasks

* [ ] https://github.com/modular-synthesizer/api/issues/24
* [ ] https://github.com/modular-synthesizer/api/issues/25
* [ ] https://github.com/modular-synthesizer/api/issues/26
